<?php

declare(strict_types=1);

return [
    'label' => 'Order',
    'plural_label' => 'Order Management',

    // Fields
    'id' => 'Order ID',
    'order_number' => 'Order Number',
    'dining_time' => 'Dining Time',
    'remarks' => 'Remarks',
    'status' => 'Order Status',
    'created_at' => 'Order Time',
    'updated_at' => 'Updated Time',

    // Status
    'status_options' => [
        'pending' => 'Pending',
        'confirmed' => 'Confirmed',
        'cooking' => 'Cooking',
        'completed' => 'Completed',
        'cancelled' => 'Cancelled',
    ],

    // Statistics
    'total_quantity' => 'Total Quantity',
    'menu_details' => 'Menu Details',
    'items_count' => 'Items Count',
    'total_items' => 'Total Items',

    // Actions
    'create' => 'Create Order',
    'edit' => 'Edit Order',
    'delete' => 'Delete Order',
    'view' => 'View Order',
    'confirm' => 'Confirm Order',
    'start_cooking' => 'Start Cooking',
    'complete' => 'Complete Order',
    'cancel' => 'Cancel Order',

    // Filters
    'filter_today' => 'Today\'s Orders',
    'filter_pending' => 'Pending',
    'filter_in_progress' => 'In Progress',
    'all_status' => 'All Status',
    'dining_date' => 'Dining Date',
    'select_date' => 'Select Date',

    // Form
    'form' => [
        'basic_info' => 'Order Basic Information',
        'order_items' => 'Order Items',
        'menu_list' => 'Menu List',
        'dining_time_help' => 'Please select dining time',
        'remarks_placeholder' => 'Please enter special requirements, such as no spicy...',
        'auto_generated' => 'Auto Generated by System',
    ],

    // Validation
    'validation' => [
        'order_number_required' => 'Order number is required',
        'dining_time_required' => 'Please select dining time',
        'status_required' => 'Please select order status',
        'items_required' => 'Please add at least one menu item',
    ],

    // Notifications
    'notifications' => [
        'created' => 'Order created successfully',
        'updated' => 'Order updated successfully',
        'deleted' => 'Order deleted successfully',
        'confirmed' => 'Order confirmed',
        'cooking' => 'Started cooking',
        'completed' => 'Order completed',
        'cancelled' => 'Order cancelled',
    ],
];
